title = "Test Blog"
baseURL = 'https://yoannap.github.io/content/en/pages/about.md'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# Enable emojis globally
enableEmoji = true

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = 'G-XVEX4GZF4S' # G-MEASUREMENT_ID

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'hrdark'
    tabWidth = 4

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10

[params]
  sitename = "Test Blog"
  defaultColor = "auto" # set default color mode: dark or light or auto
  description = "testing"
  mainSections = ['posts']
  goToTop = true # set to false to disable 'go to top' button

[params.author]
  intro = "Testing Author"
  name = "Test Name"
  description = "Test Describe"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
